<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ServicesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('services')->insert([
            [
                'type' => 'alkatreszkereskedo',
                'slug' => Str::slug('bardi-auto-gyula'),
                'name' => 'Bárdi Autó Gyula',
                'desc' => 'A Bárdi Autó Magyarország egyik legjelentősebb autóalkatrész-kereskedelmi vállalata.',
                'address' => '5700, Gyula, Kétegyházi út 1/a.',
                'phone' => '+36-1-555-0050',
                'email' => 'vevoszolgalat@bardiauto.hu',
                'website' => 'https://shorturl.at/Cc2Kx',
                'image' => 'bardi-auto.png',
                'rating' => 4.6,
                'opening_hours' => "hétfő 7:30–17:30\nkedd 7:30–17:30\nszerda 7:30–17:30\ncsütörtök 7:30–17:30\npéntek 7:30–17:30\nszombat 8:00–13:00\nvasárnap Zárva",
                'features' => 'Alvázszám kereső, személygépjármű, illetve haszongépjármű alkatrészek, motorkerékpár alkatrészek, cikkszámkereső, olajok, folyadékok, autóápolási cikkek, kiegészítők.',
                'lat' => 46.639982,
                'lng' => 21.262126,
                'long_desc' => 'Jelen vagyunk Romániában és Szlovákiában is, saját tulajdonú kirendeltségekkel. Büszkék vagyunk arra, hogy kínálatunk a kelet-európai régióban kiemelkedő módon minden igényt lefed. Központi raktárkészletünk több mint 4 millió árucikkből áll. Egyaránt árulunk alkatrészeket és felszerelési cikkeket személy-, és tehergépjárművekhez, motorkerékpárokhoz. Választékunkban a garázsipari berendezések széles választéka is elérhető. Kirendeltségeinken és webáruházunkban szakértő tanácsadással viszonteladó partnereinket és magánszemélyeket is kiszolgálunk.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'alkatreszkereskedo',
                'slug' => Str::slug('unix-gyula'),
                'name' => 'UNIX Gyula',
                'desc' => 'Az UNIX Autó Kft. Magyarország piacvezető autóalkatrész- kereskedelmi vállalata.',
                'address' => '5700, Gyula, Csabai út 9.',
                'phone' => '+36-1-270-8701',
                'email' => 'info@unixauto.hu',
                'website' => 'https://shorturl.at/zKCHU',
                'image' => 'unix-auto.jpg',
                'rating' => 4.4,
                'opening_hours' => "hétfő 7:30–17:30\nkedd 7:30–17:30\nszerda 7:30–17:30\ncsütörtök 7:30–17:30\npéntek 7:30–17:30\nszombat 8:00–13:00\nvasárnap Zárva",
                'features' => 'Szakmai oktatások partnereink részére, célszerszámbérlési lehetőség, gyári alkatrész ajánlatkérő rendszer, fáradt olaj és olajos veszélyes hulladék kezelési lehetőség, laboratóriumi kenőanyagelemzés, szervizinformációs szoftverek, diagnosztikai termékek.',
                'lat' => 46.643773,
                'lng' => 21.257114,
                'long_desc' => 'A hazai piac mellett jelen vagyunk Romániában és Szlovákiában is. Több, mint 500 beszállítóval állunk kapcsolatban és 10 millió darabos raktárkészletünket kirendeltségeinken, viszonteladóinknál és szervizeinkben is eléred. Magyarországon, Romániában és Szlovákiában közel 170 kirendeltségben várunk.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'alkatreszkereskedo',
                'slug' => Str::slug('olah-autoalkatresz-kis-es-nagyker'),
                'name' => 'Oláh Autóalkatrész kis- és nagyker',
                'desc' => 'Autóalkatrész kis- és nagykereskedés hálózat az ország több pontján.',
                'address' => '5700, Gyula, Nagyváradi út 10.',
                'phone' => '+36-20-61-61-100',
                'email' => 'oft@olahauto.hu',
                'website' => 'https://shorturl.at/XlFdB',
                'image' => 'olah-auto.jpg',
                'rating' => 4.8,
                'opening_hours' => "hétfő 8:00–17:00\nkedd 8:00–17:00\nszerda 8:00–17:00\ncsütörtök 8:00–17:00\npéntek 8:00–17:00\nszombat Zárva\nvasárnap Zárva",
                'features' => 'Gépjármű gyorsszervíz, autóalkatrész kereskedés, ioncserélt víz csomagolás, gumiharang.',
                'lat' => 46.648128,
                'lng' => 21.284301,
                'long_desc' => '35 éves üzleti tapasztalatnak és pénzügyi stabilitásnak köszönhetõen jelenleg Békés megyében 4 üzletben várjuk vásárlóinkat, melyeket 4000 m2-es gyulai központi raktárbázisunkból látunk el. Budapesten logisztikai telephellyel rendelkezünk. A külkereskedelem liberalizációja óta export-import tevékenységet folytatunk, fõbb partnereink Ukrajnában, Litvániában, Bulgáriában, Kínában, Tajvanon és az Európai Unión belül találhatók.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'alkatreszkereskedo',
                'slug' => Str::slug('po-alkatresz-kft'),
                'name' => 'P.O. Alkatrész Kft.',
                'desc' => 'A 2009 óta működő cégünk személygépkocsi és kisteherautó alkatrészek kis- és nagykereskedelmével foglalkozik.',
                'address' => '5700 Gyula, Szent István u. 25/b.',
                'phone' => '+36-66-633-888',
                'email' => 'poauto@poauto.hu',
                'website' => 'https://shorturl.at/eK0kd',
                'image' => null,
                'rating' => 5.0,
                'opening_hours' => "hétfő 8:00–17:00\nkedd 8:00–17:00\nszerda 8:00–17:00\ncsütörtök 8:00–17:00\npéntek 8:00–17:00\nszombat 09:00–12:00\nvasárnap Zárva",
                'features' => 'Motor kopóalkatrészek, autóalkatrészek.',
                'lat' => 46.640491,
                'lng' => 21.274444,
                'long_desc' => 'A P.O üzletében Ön elérhető áron vásárolhatja meg a kiváló minőségű alkatrészeket: után gyártott esetében raktárkészletünkből, illetve 1 napos beszerzési határidővel, de gyári alkatrészeket is beszerzünk Önnek rövid teljesítési idővel. Ezen felül vállaljuk a megrendelt alkatrészek postai úton történő elszállítását is.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'alkatreszkereskedo',
                'slug' => Str::slug('car-potlas-autobonto'),
                'name' => 'Car-Pótlás Autóbontó',
                'desc' => 'Jelenleg több mint 20.000 m2-es területen tevékenykedünk.',
                'address' => '5700, Gyula, 44-es főút, 134.km',
                'phone' => '+36-30-638-8398',
                'email' => 'matyitomi@yahoo.com',
                'website' => 'https://shorturl.at/9Bshn',
                'image' => 'car-potlas.jpg',
                'rating' => 4.6,
                'opening_hours' => "hétfő 7:30–12:00, 12:30–16:00\nkedd 7:30–12:00, 12:30–16:00\nszerda 7:30–12:00, 12:30–16:00\ncsütörtök 7:30–12:00, 12:30–16:00\npéntek Zárva\nszombat Zárva\nvasárnap Zárva",
                'features' => 'Autómentés, autóbontás, alkatrészkereskedelem, gépszállítás.',
                'lat' => 46.653616,
                'lng' => 21.230711,
                'long_desc' => 'A használt alkatrészeket megfelelő minősítéssel, a beépíthetőnek minősítetteket beszerelési garanciával, - igény szerint akár beszerelve-, kedvező áron kínáljuk a tisztelt ügyfelek részére. Törzsvásárlóinknak, szerelőknek, illetve nagyobb tételben vásárlóknak jelentős kedvezményeket biztosítunk!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'alkatreszkereskedo',
                'slug' => Str::slug('roadster-autobonto-kft'),
                'name' => 'Roadster Autóbontó Kft.',
                'desc' => 'A Roadster Autóbontó Kft. 1993-ban indult egy mindössze 120 négyzetméteres műhellyel. Azóta folyamatosan fejlődtünk és bővültünk, így napjainkra 1,6 hektáros modern telephelyen állunk ügyfeleink rendelkezésére.',
                'address' => '5600 Békéscsaba, Szarvasi út 115.',
                'phone' => '+36-20-210-0312',
                'email' => 'roadster@autobontocsaba.hu',
                'website' => 'https://shorturl.at/QRIlY',
                'image' => 'roadster.webp',
                'rating' => 4.2,
                'opening_hours' => "hétfő 07:30–16:30\nkedd 07:30–16:30\nszerda 07:30–16:30\ncsütörtök 07:30–16:30\npéntek 07:30–16:30\nszombat 07:30–12:30\nvasárnap Zárva",
                'features' => 'Sérült, törött személyautók és kisteherautók felvásárlása, szakszerű bontás és alkatrészek széles választéka.',
                'lat' => 46.684925,
                'lng' => 21.053877,
                'long_desc' => 'A Roadster Autóbontó Békéscsabán megbízható partner használt autóalkatrészek beszerzésében. Széles választékkal, szakszerű kiszolgálással és korrekt árakkal várják ügyfeleiket, legyen szó autófelvásárlásról vagy alkatrészvásárlásról.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'alkatreszkereskedo',
                'slug' => Str::slug('szakal-metal-autoalkatresz-bekescsaba'),
                'name' => 'Szakál Metal Autóalkatrész Békéscsaba',
                'desc' => 'Cégünk folyamatos és intenzív fejlődése közben megőrizte a motorikus alkatrészben szerzett elsőségét, de kiterjesztette kínálati palettáját a szerviz alkatrészek széles körére és a kenőolajok forgalmazására is.',
                'address' => '5600 Békéscsaba, Szarvasi út 13/1.',
                'phone' => '+36-20-487-4234',
                'email' => 'bekescsaba@szakalmetal.hu',
                'website' => 'https://shorturl.at/oaeZz',
                'image' => 'szakalmetal.png',
                'rating' => 4.8,
                'opening_hours' => "hétfő 8:00–17:00\nkedd 8:00–17:00\nszerda 8:00–17:00\ncsütörtök 8:00–17:00\npéntek 8:00–17:00\nszombat Zárva\nvasárnap Zárva",
                'features' => 'Alkatrész értékesítés, motorfelújítás, autójavítás.',
                'lat' => 46.686107,
                'lng' => 21.088653,
                'long_desc' => 'A Szakál-Met-Al Zrt az 1946-os alapítása óta eltelt, több mint 70 év során egyedülálló szakmai tapasztalatokra és tudásra tett szert a személy-és tehergépkocsik motorikus alkatrészeinek, szerviz alkatrészeinek értékesítése során, és az autójavítás terén. Ez lehetővé tette számunkra, hogy cégfilozófiánkkal összhangban, felépítsük Közép-Európa legnagyobb motorikus autóalkatrész kereskedését.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'alkatreszkereskedo',
                'slug' => Str::slug('inter-cars-bekescsaba'),
                'name' => 'Inter Cars Békéscsaba',
                'desc' => 'Az Inter Cars Hungária Kft. Magyarország egyik meghatározó autóalkatrész kereskedelmi szereplője.',
                'address' => '5600 Békéscsaba, Orosházi út 2.',
                'phone' => '+36-20-429-7205',
                'email' => 'bekescsaba@intercars.eu',
                'website' => 'https://shorturl.at/ocCsT',
                'image' => 'intercar.jpeg',
                'rating' => 4.8,
                'opening_hours' => "hétfő 8:00–17:00\nkedd 8:00–17:00\nszerda 8:00–17:00\ncsütörtök 8:00–17:00\npéntek 8:00–17:00\nszombat 8:00–12:00\nvasárnap Zárva",
                'features' => 'Autóalkatrész kis- és nagykereskedés.',
                'lat' => 46.664169,
                'lng' => 21.079612,
                'long_desc' => 'Az Inter Cars Kelet- és Közép-Európa 21 országában van jelen. Az európai alkatrészpiac meghatározó tagjaként Magyarországon is a folyamatos fejlődés hitében dolgozunk nap, mint nap. Autóipari ismereteinket immár 34. éve bővítjük és fordítjuk Ügyfeleink kiszolgálására.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'alkatreszkereskedo',
                'slug' => Str::slug('kellner-es-fia-autobonto'),
                'name' => 'KELLNER ÉS FIA autóbontó',
                'desc' => 'A KELLNER ÉS FIA autóbontó - bontási átvételi igazolás kiadásával - készpénzért megvásárol minden típusú karambolos, törött, sérült, roncs, lejárt műszakis, üzemképtelen, korrodált, külföldi rendszámos, stb. gépjárművet bontásra, megsemmisítésre.',
                'address' => '5600, Békéscsaba, Ipari út 17.',
                'phone' => '+36-66-443-468',
                'email' => 'letra5@invitel.hu',
                'website' => 'https://shorturl.at/5XDxE',
                'image' => null,
                'rating' => 4.3,
                'opening_hours' => "hétfő 8:00-12:00, 13:00-17:00\nkedd 8:00-12:00, 13:00-17:00\nszerda 8:00-12:00 ,13:00-17:00\ncsütörtök 8:00-12:00, 13:00-17:00\npéntek 8:00-12:00, 13:00-17:00\nszombat 8:00–12:00\nvasárnap Zárva",
                'features' => 'Bevizsgált alkatrészek értékesítése, gyári és után gyártott alkatrészek értékesítése, veterán autó, autóbusz, teherautó, gépkocsi, gépjármű, motor, kerékpár alkatrészek és könyvek értékesítése.',
                'lat' => 46.695677,
                'lng' => 21.076180,
                'long_desc' => 'A Kellner és Fia Autóbontó megbízható, hosszú évek óta működő családi vállalkozás, ahol használt, de jó állapotú autóalkatrészek széles választéka várja a vásárlókat. Bontás, alkatrész-keresés és környezetbarát újrahasznosítás egy helyen.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'alkatreszkereskedo',
                'slug' => Str::slug('mobil-sapiens-kft-autoolkatresz-szakuzlet'),
                'name' => 'MOBIL-SAPIENS KFT. Autóalkatrész szaküzlet',
                'desc' => 'Cégünk gyári és utángyártott alkatrészek kis- és nagykereskedelmével, valamint személy és kishaszonjárművek javításával foglalkozik.',
                'address' => '5600 Békéscsaba, Szarvasi út 45.',
                'phone' => '+36-66-454-731',
                'email' => 'msauto@msauto.hu',
                'website' => 'https://shorturl.at/FxumC',
                'image' => 'mobilsapiens.png',
                'rating' => 5,
                'opening_hours' => "hétfő 8:00 - 17:00\nkedd 8:00 - 17:00\nszerda 8:00 - 17:00\ncsütörtök 8:00 - 17:00\npéntek 8:00 - 17:00\nszombat 9:00 - 12:00\nvasárnap Zárva",
                'features' => 'Gyári és utángyártott alkatrészek kis- és nagykereskedelme.',
                'lat' => 46.683121,
                'lng' => 21.079928,
                'long_desc' => 'Raktárunkban nem lévő régi és új típusú autók alkatrészeit 24 órás szállítási határidővel beszerezzük. Baráti áraink nem csak régi ügyfeleink számára elérhetők! Minden tipusú autóhoz megtalálja nálunk alkatrészét, kiegészítőjét!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'alkatreszkereskedo',
                'slug' => Str::slug('lang-autoalkatresz-bekescsaba'),
                'name' => 'Láng Autóalkatrész Békéscsaba',
                'desc' => 'Láng Kft. az LKQ csoport tagjaként Európa legnagyobb autóalkatrész kereskedelmi hálózatának magyarországi tagja, alkatrészek, autótartozékok és autós cikkek szállítója.',
                'address' => '5600, Békéscsaba, Ipari út 42.',
                'phone' => '+36-66-524-200',
                'email' => 'info@langauto.hu',
                'website' => 'https://shorturl.at/BdkWH',
                'image' => 'lang.png',
                'rating' => 4.6,
                'opening_hours' => "hétfő 8:00–17:00\nkedd 8:00–17:00\nszerda 8:00–17:00\ncsütörtök 8:00–17:00\npéntek 8:00–17:00\nszombat 8:00–12:00\nvasárnap Zárva",
                'features' => 'Alkatrészek kis- és nagykereskedelme.',
                'lat' => 46.695213,
                'lng' => 21.077975,
                'long_desc' => 'Autószervizek kiemelt beszállítójaként üzleteink országos hálózattal széles választékot kínálnak partnereinknek Magyarországon és Európa nagy részén. Magyarországon 26 telephellyel és több mint 500 munkatárssal állunk vevőink rendelkezésére.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'alkatreszkereskedo',
                'slug' => Str::slug('toth-autosbolt'),
                'name' => 'Tóth Autósbolt',
                'desc' => 'A Sarkadi Tóth Autósbolt minőségi autóalkatrészekkel, barátságos kiszolgálással és gyors beszerzéssel várja vásárlóit Sarkadon személyautókhoz.',
                'address' => '5720, Sarkad, Gyulai út 1.',
                'phone' => '+36-66-270-548',
                'email' => null,
                'website' => null,
                'image' => null,
                'rating' => 5.0,
                'opening_hours' => "hétfő 8:00–18:00\nkedd 8:00–18:00\nszerda 8:00–18:00\ncsütörtök 8:00–18:00\npéntek 8:00–18:00\nszombat 8:00–13:00\nvasárnap Zárva",
                'features' => 'Alkatrész kereskedés, alkatrész felújítás.',
                'lat' => 46.739306,
                'lng' => 21.373217,
                'long_desc' => 'A Sarkadi Tóth Autósbolt megbízható választás mindazoknak, akik minőségi autóalkatrészeket keresnek kedvező áron. Legyen szó kopó-fogyó alkatrészekről, motorikus elemekről vagy autós kiegészítőkről, a bolt széles kínálatot nyújt!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'alkatreszkereskedo',
                'slug' => Str::slug('erdos-autosbolt'),
                'name' => 'Erdős Autósbolt',
                'desc' => 'Az Erdős Autósbolt Eleken széles választékot kínál autó-, motor-, kisteherautó- és utánfutó-alkatrészekből, valamint felszerelési cikkekből, karosszériaelemekből, kipufogókból és kenőanyagokból.',
                'address' => '5742, Elek, Lökösházi út 14.',
                'phone' => '+36-20-342-4391',
                'email' => 'erdoskrisztian77@gmail.com',
                'website' => 'https://shorturl.at/oM7SQ',
                'image' => null,
                'rating' => 4.5,
                'opening_hours' => "hétfő 8:00–16:00\nkedd 8:00–16:00\nszerda 8:00–16:00\ncsütörtök 8:00–16:00\npéntek 8:00–16:00\nszombat 8:00–12:00\nvasárnap ZÁRVA",
                'features' => 'Autó-, motor-, kisteherautó-, utánfutóalkatrészek, felszerelési cikkek, karosszéria elemek, kipufogók és olajok/adalékok.',
                'lat' => 46.527670,
                'lng' => 21.251908,
                'long_desc' => 'A bolt célja, hogy megbízható és gyors kiszolgálással segítse a járműtulajdonosokat a szükséges alkatrészek beszerzésében. A helyi jelenlét és a szakértői tanácsadás révén az Erdős Autósbolt kiemelkedik a környékbeli autóalkatrész-kereskedések közül.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'autoszerelo',
                'slug' => Str::slug('somogyi-autoszerelo-muhely'),
                'name' => 'Somogyi Autószerelő Műhely',
                'desc' => 'Folyamatosan biztosítjuk a műhelyünkben a személygépkocsik és tehergépjárművek szervizelését, karbantartását, műszaki vizsgáztatását.',
                'address' => '5700, Gyula, Cinka Panna u. 19-21.',
                'phone' => '+36-30-501-2247',
                'email' => 'somogyiautoszervizplusz@gmail.com',
                'website' => 'https://shorturl.at/qeCOt',
                'image' => null,
                'rating' => 4.5,
                'opening_hours' => "hétfő 8:00–17:00\nkedd 8:00–17:00\nszerda 8:00–17:00\ncsütörtök 8:00–17:00\npéntek 8:00–17:00\nszombat Zárva\nvasárnap Zárva",
                'features' => 'Autóvillamosság, autóelektronika szerelés, műszaki vizsgára felkészítés, autószerelés, állapotfelmérés, motordiagnosztika, olajcsere, fékrendszerek speciális javítása.',
                'lat' => 46.638124,
                'lng' => 21.269983,
                'long_desc' => 'A műhely munkatársai rendkívül segítőkészek, gyorsak és precízek, gyakran túllépve az elvárható szinten. Számos ügyfél kiemelte a korrekt kommunikációt, a tájékoztatás minőségét és a váratlan helyzetekben nyújtott segítséget. A műhely vezetője és csapata nemcsak szakmailag kiváló, hanem emberségük és kedvességük miatt is kiemelkedő. Az ügyfelek többsége szívből ajánlja a műhelyt, különösen azoknak, akik kiváló szakemberekre és megbízható szolgáltatásra vágynak.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'autoszerelo',
                'slug' => Str::slug('gamma-autoszerviz-es-autokozmetika'),
                'name' => 'Gamma Autószerviz & Autókozmetika',
                'desc' => 'A Gamma Autószerviz továbbra is várja meglévő és leendő ügyfeleit!',
                'address' => '5700, Gyula, Csabai út 135.',
                'phone' => '+36-30-725-4899',
                'email' => 'service@gammatrans.hu',
                'website' => 'https://shorturl.at/CuOSc',
                'image' => 'gamma-autoszerviz.jpg',
                'rating' => 4.8,
                'opening_hours' => "hétfő 8:00–17:00\nkedd 8:00–17:00\nszerda 8:00–17:00\ncsütörtök 8:00–17:00\npéntek 8:00–17:00\nszombat Zárva\nvasárnap Zárva",
                'features' => 'Autószerelés szolgáltatás, autóbróker, autótakarítás és mosás.',
                'lat' => 46.651826,
                'lng' => 21.245019,
                'long_desc' => 'Megfelelő választás, ha eladásra kerül a sor, viszont ha egy szerelés vár az autódra, azt is megoldhatod itt.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'autoszerelo',
                'slug' => Str::slug('lengyel-autoszerviz'),
                'name' => 'Lengyel Autószerviz',
                'desc' => 'Tökéletes választás egy műszaki vizsga előtti átnézésre, esetleges javításra Gyulán!',
                'address' => '5700, Gyula, Dobozi út 28.',
                'phone' => '+36-30-958-9429',
                'email' => 'kipufogoszakszerviz@t-online.hu',
                'website' => 'https://shorturl.at/5tuDB',
                'image' => 'lengyel-autoszerviz.jpg',
                'rating' => 4.6,
                'opening_hours' => "hétfő 8:00–17:00\nkedd 8:00–17:00\nszerda 8:00–17:00\ncsütörtök 8:00–17:00\npéntek 8:00–17:00\nszombat Zárva\nvasárnap Zárva",
                'features' => 'Márkafüggetlen gépjárműjavítás (futó és nagyjavítások), gumiszerelés, futómű javítás és állítás, diagnosztika, lakatos munkák, kipufogó katalizátor javítás és csere.',
                'lat' => 46.661256,
                'lng' => 21.277925,
                'long_desc' => 'A munka megkezdése előtt minden esetben megbeszéljük Önnel a szükséges munkálatokat. Szakképzett csapatunk mindent megtesz az Ön autójáért. Mindig gyorsan és az igényeinek megfelelően tesszük a dolgunkat. Számunkra mindig fontos szempont a magas színvonalú szolgáltatás versenyképes áron.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'autoszerelo',
                'slug' => Str::slug('kempf-auto'),
                'name' => 'Kempf Autó',
                'desc' => 'Megbízható Bosch szervíz, illetve vizsgaközpont, ahol egészen 3,5 T súlyig minden jármű megfordul!',
                'address' => '5700, Gyula, Kétegyházi út 8.',
                'phone' => '+36-70-457-5700',
                'email' => 'info@kempf.hu',
                'website' => 'https://shorturl.at/cBeOf',
                'image' => 'kempf-auto.jpg',
                'rating' => 4.6,
                'opening_hours' => "hétfő 8:00–17:00\nkedd 8:00–17:00\nszerda 8:00–17:00\ncsütörtök 8:00–17:00\npéntek 8:00–17:00\nszombat Zárva\nvasárnap Zárva",
                'features' => 'Általános szervizelés, műszaki vizsgáztatás, eredetiség vizsgálat, autóvillamosság, gumi szerelés/javítás, futómű állítás/javítás, fék szerviz, autódiagnosztika.',
                'lat' => 46.632934,
                'lng' => 21.258109,
                'long_desc' => 'Szerelőink gőz erővel dolgoznak nap, mint nap azon, hogy a hasonló életmentő műtéteket precízen és szakszerűen elvégezzék az Ügyfeleink autóin!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'autoszerelo',
                'slug' => Str::slug('marsopont-bekescsaba'),
                'name' => 'MARSOPONT Békéscsaba',
                'desc' => 'Tudtad, hogy ma Magyarországon minden személyautón legalább 1db gumiabroncs a MARSO raktárából származik?',
                'address' => '5600, Békéscsaba Szarvasi út 84.',
                'phone' => '+36-66-328-588',
                'email' => null,
                'website' => 'https://shorturl.at/crQk0',
                'image' => 'marso.png',
                'rating' => 4.5,
                'opening_hours' => "hétfő 08:00–18:00\nkedd 08:00–18:00\nszerda 08:00–18:00\ncsütörtök 08:00–18:00\npéntek 08:00–18:00\nszombat 08:00–13:00\nvasárnap Zárva",
                'features' => 'Autószerviz, gumiszerviz, kerékszerviz.',
                'lat' => 46.684103,
                'lng' => 21.055927,
                'long_desc' => 'Békéscsabai MARSOPONT szervizünkben szervizszolgáltatásaink sokrétű palettájával várunk, akár autód gumiabroncsait kell lecserélni, akár más autószervizhez kapcsolódó szolgáltatást szeretnél igénybe venni.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'autoszerelo',
                'slug' => Str::slug('auto-dual-bekescsaba'),
                'name' => 'Autó Dual Békéscsaba',
                'desc' => 'Az Autó Dual vezetői és dolgozói napról-napra azért dolgozunk, hogy a bennünket felkereső érdeklődőkből minél többen elégedett vásárlóinkká váljanak, akik szívesen térnek vissza hozzánk!',
                'address' => '5600, Békéscsaba, Szarvasi út 117.',
                'phone' => '+36-20-80-48-666',
                'email' => 'ugyfelszolgalat@autodual.hu',
                'website' => 'https://shorturl.at/ti75i',
                'image' => 'autodual.jpeg',
                'rating' => 4.2,
                'opening_hours' => "hétfő 9:00–18:00\nkedd 9:00–18:00\nszerda 9:00–18:00\ncsütörtök 9:00–18:00\npéntek 9:00–18:00\nszombat 9:00–16:00\nvasárnap Zárva",
                'features' => 'Időszakos márkafüggetlen karbantartás, javítás.',
                'lat' => 46.685058,
                'lng' => 21.052929  ,
                'long_desc' => 'Ahogy szlogenünkben is mondjuk, „Nézzen körül nálunk”! Akár személyesen akár interneten keresztül keres fel bennünket bízunk benne, hogy megtalálja az Önnek leginkább megfelelő autót, amelynek kiválasztásához, finanszírozásához és rendszeres szervizeléséhez minden tőlünk telhető szakmai segítséget megadunk.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'autoszerelo',
                'slug' => Str::slug('egeresi-autoszerviz'),
                'name' => 'Egeresi Autószerviz',
                'desc' => 'A szerviz fő profilja a teljeskörű motorfelújítás és -javítás, valamint autódiagnosztika és műszaki vizsgára való felkészítés.',
                'address' => '5600, Békéscsaba, Kinizsi u.11.',
                'phone' => '+36-30-963-0861',
                'email' => 'egeresi.sandor01@gmail.com',
                'website' => 'https://shorturl.at/plSly',
                'image' => 'egeresi.jpeg',
                'rating' => 4.9,
                'opening_hours' => "hétfő 8:00–17:00\nkedd 8:00–17:00\nszerda 8:00–17:00\ncsütörtök 8:00–17:00\npéntek 8:00–17:00\nszombat 9:00–12:00\nvasárnap Zárva",
                'features' => 'Teljeskörű motorfelújítás és -javítás, autódiagnosztika, felkészítés műszaki vizsgára.',
                'lat' => 46.680327,
                'lng' => 21.093140,
                'long_desc' => 'Az ügyfelek különösen dicsérik a szerviz rugalmasságát, korrektségét és barátságos kiszolgálását. A családias hangulat és a korszerű felszereltség is hozzájárul a pozitív tapasztalatokhoz.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'autoszerelo',
                'slug' => Str::slug('m-fem-kft'),
                'name' => 'M-Fém Kft.',
                'desc' => 'Autószerelés, autódiagnosztika, autóvillamossági szerelés, motorfelújítás, futómű állítás, autó klímajavítás, fékmérés, lengéscsillapító mérés, futómű holtjátékvizsgálás, kipufogó szerviz, karosszéria javítás, műszaki vizsgára felkészítés, mezőgazdasági gumiszerelés és új gumik forgalmazása, személyautó gumiszerelés.',
                'address' => '5720, Sarkad, Széles u. 7/A',
                'phone' => '+36-66-787-852',
                'email' => 'mfemkft@gmail.com',
                'website' => 'https://shorturl.at/Pg9ak',
                'image' => 'mfem.png',
                'rating' => 5,
                'opening_hours' => "hétfő 08:00–17:00\nkedd 08:00–17:00\nszerda 08:00–17:00\ncsütörtök 08:00–17:00\npéntek 08:00–17:00\nszombat Zárva\nvasárnap Zárva",
                'features' => 'Autószerelés, autódiagnosztika, autóvillamossági szerelés, motorfelújítás, futómű állítás, autó klímajavítás, fékmérés, lengéscsillapító mérés, futómű holtjátékvizsgálás, kipufogó szerviz, karosszéria javítás, műszaki vizsgára felkészítés, mezőgazdasági gumiszerelés és új gumik forgalmazása, személyautó gumiszerelés.',
                'lat' => 46.748456,
                'lng' => 21.380491,
                'long_desc' => 'Várjuk Önt és autóját, több mint 15 év autószervizelési tapasztalattal, szakértő munkatársakkal és jól felszerelt műhellyel! Mindenre kiterjedő autószerelési szolgáltatásokkal állunk rendelkezésére, az időszakos szerviztől a műszaki vizsgán át az autódiagnosztikáig, márkafüggetlen szervizünk a személyautó és terepjáró és kisteherautó és hibrid járművek szervizelését is vállalja, kollégáink klíma javítás terén is nagy tapasztalattal és szakképesítéssel rendelkeznek!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'autoszerelo',
                'slug' => Str::slug('szervizpont'),
                'name' => 'Szervizpont',
                'desc' => 'Autómentés, műszaki mentés, teljes körű gépjármű javítás, személyautó diagnosztika, futómű beállítás, karosszária javítás és fényezés, alsó és felső mosás, műszaki vizsgáztatás előzetes teljes átvizsgálással.',
                'address' => '5600, Békéscsaba, Balassa utca 14.',
                'phone' => '+36-30-228-24-47',
                'email' => 'szerviz@szervizpont.com',
                'website' => 'https://shorturl.at/xHnN2',
                'image' => 'szervizpont.png',
                'rating' => 4.6,
                'opening_hours' => '24 órában a 7 minden napján',
                'features' => 'Autómentés, műszaki mentés, teljes körű gépjármű javítás, személyautó diagnosztika, futómű beállítás, karosszária javítás és fényezés, alsó és felső mosás, műszaki vizsgáztatás előzetes teljes átvizsgálással.',
                'lat' => 46.698232,
                'lng' => 21.080269,
                'long_desc' => 'Keresse a hét minden napján, 24 órában elérhető ügyintézőnket, ha szervizelésre van szüksége. Precíz, kifogásolhatatlan kitartással rendelkező kollégáink fényt derítenek a problémákra és meg is oldják azokat a több éves munkatapasztalatunknak köszönhetően!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'autoszerelo',
                'slug' => Str::slug('kertesz-auto-kft'),
                'name' => 'Kertész Autó Kft.',
                'desc' => 'Gépjármű diagnosztika, gépjármű javítás, futómű állítás, alváz és motormosás.',
                'address' => '5600, Békéscsaba, Széna utca 1.',
                'phone' => '+36-30-0808-000',
                'email' => 'info@kerteszauto.hu',
                'website' => 'https://shorturl.at/mN9M6',
                'image' => 'kertesz.png',
                'rating' => 5,
                'opening_hours' => "hétfő 7:30-16:00\nkedd 7:30-16:00\nszerda 7:30-16:00\ncsütörtök 7:30-16:00\npéntek 7:30-13:30\nszombat Zárva\nvasárnap Zárva",
                'features' => 'Gépjármű diagnosztika, gépjármű javítás, futómű állítás, alváz és motormosás.',
                'lat' => 46.691627,
                'lng' => 21.070792,
                'long_desc' => 'A tulajdonos Kertész János az autószerelő szakma elhivatott alakja, aki 2004-ben az aranykoszorús mesteri kitüntető címet is kiérdemelte. 2019 januárjától elérhető legújabb szolgáltatásunk a 3D-s futómű beállítás, melyet a legkorszerűbb Hunter Hawkeye Elite futóműbeállítóval végzünk. Ha felkeltettük érdeklődését, forduljon hozzánk bizalommal, kollégáink készségesen állnak rendelkezésére!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'autoszerelo',
                'slug' => Str::slug('pal-autojavito-kft'),
                'name' => 'Pál Autójavító Kft.',
                'desc' => 'Autószerviz, hozom-viszem szolgáltatás.',
                'address' => '5600, Békéscsaba, Tessedik utca 51.',
                'phone' => '+36-66-528-528',
                'email' => null,
                'website' => 'https://shorturl.at/tojJW',
                'image' => 'pal-auto.png',
                'rating' => 4.5,
                'opening_hours' => "hétfő 8:00–16:30\nkedd 8:00–16:30\nszerda 8:00–16:30\ncsütörtök 8:00–16:30\npéntek 8:00–16:00\nszombat Zárva\nvasárnap Zárva",
                'features' => 'Autószerviz, hozom-viszem szolgáltatás.',
                'lat' => 46.667817,
                'lng' => 21.088717,
                'long_desc' => 'Több, mint 10 éves tapasztalattal a hátunk mögött, szakmájukat kiválóan kitanult kollégáink minden hiba forrását felderítik. Minden alkatrészre garanciát vállalunk, ha hibás a termék, cseréljük vagy feltárjuk a lehetséges hibalehetőségeket!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'autoszerelo',
                'slug' => Str::slug('four-wheel-drive-bt'),
                'name' => 'Four Wheel Drive Bt.',
                'desc' => 'Teljes körű gépjármű javítás, karbantartás, karosszériázás, fényezés, műszaki vízsgáztatás.',
                'address' => '5720, Sarkad, Sarkadkeresztúri út 51.',
                'phone' => '+36-70-626-6030',
                'email' => null,
                'website' => 'https://shorturl.at/dUPoT',
                'image' => null,
                'rating' => 4,
                'opening_hours' => "hétfő 8:00-12:00, 13:00-17:00\nkedd 8:00-12:00, 13:00-17:00\nszerda 8:00-12:00, 13:00-17:00\ncsütörtök 8:00-12:00, 13:00-17:00\npéntek 8:00-12:00, 13:00-17:00\nszombat 9:00–13:00\nvasárnap Zárva",
                'features' => 'Teljes körű gépjármű javítás, karbantartás, karosszériázás, fényezés, műszaki vízsgáztatás, robbanómotoros kisgépek javítása.',
                'lat' => 46.753580,
                'lng' => 21.382131,
                'long_desc' => 'Ha olyan szervizt keresel, ahol nemcsak a munkát végzik el precízen, hanem valóban törődnek az autóddal is, akkor a Four Wheel Drive Bt.-nél a helyed! Sarkad szélén, nyugodt környezetben profi csapat vár, legyen szó motorjavításról, fényezésről vagy műszaki vizsgáról. Ők nem csak “megjavítják”, hanem új életet lehelnek a járművedbe – mindezt korrekt áron, barátságos hangulatban. Itt nem csak az autód, te is jó kezekben leszel.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'gumiszerviz',
                'slug' => Str::slug('gyulai-gumiszerviz-kft'),
                'name' => 'Gyulai Gumiszerviz Kft.',
                'desc' => 'Cégünk gyorsan és rugalmasan reagál bármilyen egyedi megrendelés esetén is. Tervezzük az eszközpark fejlesztését a fokozott minőségi elvárások érdekében.',
                'address' => '5700, Gyula, Bicere 14/a.',
                'phone' => '+36 20 345 7150',
                'email' => 'info@gyulaigumiszerviz.hu',
                'website' => 'https://shorturl.at/YkhdN',
                'image' => 'gyulai-gumiszerviz.jpg',
                'rating' => 4.8,
                'opening_hours' => "hétfő 8:00–16:00\nkedd 8:00–16:00\nszerda 8:00–16:00\ncsütörtök 8:00–16:00\npéntek 8:00–16:00\nszombat 8:00–12:00\nvasárnap Zárva",
                'features' => 'Személygépkocsi, teherautó, kamion, motor és kerékpár, haszongépjármű gumiabroncsok forgalmazása, gumiabroncsok javítása, szerelés, centrírozás, keréktárolás, szaktanácsadás.',
                'lat' => 46.654945,
                'lng' => 21.237890,
                'long_desc' => '2013 őszén vállalkozásunk megnyitotta Gumiszerviz részlegét, ahol igyekszünk szintén teljes körű szolgáltatást nyújtani. Tevékenységi körünkbe tartozik többek között személygépkocsi, teherautó, kamion, motor és kerékpár, haszongépjármű gumiabroncsok forgalmazása, javítása, szerelése, centírozása.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'gumiszerviz',
                'slug' => Str::slug('pneubox-kft'),
                'name' => 'PNEUBOX Kft.',
                'desc' => 'Cégünk 2005-ben alakult fő profilunk a gumiabroncsok kereskedelme, szerelése és javítása. 2013 óta megújult környezetben várjuk kedves ügyfeleinket.',
                'address' => '5700, Gyula, Kétegyházi út 7/a.',
                'phone' => '+36-30-325-97-97',
                'email' => 'pneuboxkft@gmail.com',
                'website' => 'https://shorturl.at/uVwWx',
                'image' => null,
                'rating' => 5,
                'opening_hours' => "hétfő 7:30-17:00\nkedd 7:30-17:00\nszerda 7:30-17:00\ncsütörtök 7:30-17:00\npéntek 7:30-17:00\nszombat 8:00-12:00\nvasárnap Zárva\nebédszünet 12:00-12:30",
                'features' => 'Gumiszerelés, gumijavítás, keréktárcsa javítás, új és használt gumiabroncsok, tömlők, gumiabroncs tárolás.',
                'lat' => 46.634353,
                'lng' => 21.258005,
                'long_desc' => 'Szervizünk felszereltsége és szakembereink képzettsége révén minden egyes ügyfelünket maximális szakértelemmel szolgáljuk ki. Minőségi szolgáltatást nyújtunk a legmodernebb gépekkel és minőségi anyagokkal. A gumijavítást tapasztalt szakembereink gyorsan és megbízhatóan végzik el. A felhasznált anyagok kimagasló minősége és a csúcstechnológiás gépek alkalmazása ugyancsak az ügyfeleink biztonságát szolgálják.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'gumiszerviz',
                'slug' => Str::slug('kolus-trade-kft'),
                'name' => 'KÖLÜS-TRADE Kft.',
                'desc' => 'Hatalmas gumiválasztékkal vár a Gyulaváriban található, könnyen megközelíthető szervizkomplexum!',
                'address' => '5711, Gyula Temesvári út 69.',
                'phone' => '+36-20-3993-100',
                'email' => 'info@kolustrade.hu',
                'website' => 'https://shorturl.at/Myamg',
                'image' => 'kolustrade.png',
                'rating' => 4.7,
                'opening_hours' => "hétfő 8.00-17.00\nkedd 8.00-17.00\nszerda 8.00-17.00\ncsütörtök 8.00-17.00\npéntek 8.00-17.00\nszombat 8.00-12.00\nvasárnap Zárva",
                'features' => 'Kerékpár értékesítés, kerti kisgépek, gumiabroncsok cseréje és szervizelése, munkagépek abroncsainak forgalmazása és cseréje.',
                'lat' => 46.635741,
                'lng' => 21.298369,
                'long_desc' => 'Ha azonnali gumicserére van szükséged, itt megoldják a problémáid! Korszerű gépek és munkaeszközök segítségével, egy pörgős csapat várja a kedves leendő, illetve már meglévő vendégeket!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'gumiszerviz',
                'slug' => Str::slug('filo-gumiszerviz'),
                'name' => 'Filó Gumiszerviz',
                'desc' => 'Könnyen elérhető, nagy raktárkészlettel rendelkező gumiszerviz Gyula belvárosában.',
                'address' => '5700, Gyula, Csabai út 40.',
                'phone' => '+36-20-957-2406',
                'email' => 'filobt@t-online.hu',
                'website' => 'https://shorturl.at/Q0z8L',
                'image' => null,
                'rating' => 5,
                'opening_hours' => "hétfő 08:00-17:00\nkedd 08:00-17:00\nszerda 08:00-17:00\ncsütörtök 08:00-17:00\npéntek 08:00-17:00\nszombat 09:00-12:00\nvasárnap Zárva",
                'features' => 'Alufelni szerelés, centírozás, gumiabroncs kereskedés.',
                'lat' => 46.644114,
                'lng' => 21.257243,
                'long_desc' => 'A városba vezető utcán található gumiszervizben szakemberek végzik a munkát, ezzel minőséget biztosítva ügyfeleiknek.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'gumiszerviz',
                'slug' => Str::slug('auto-klima-es-gumiabroncs-szerviz'),
                'name' => 'Autóklíma és Gumiabroncs Szervíz',
                'desc' => 'Akár szezonális gumicsere vagy defekt miatt érkezel, itt hamar és pénztárcabarát módon juthatsz új abrocsaidhoz! Sőt, még a klímádat is kitisztíttathatod, hiszen itt ezzel is foglalkoznak!',
                'address' => '5700, Gyula, Sarkadi út 5. (bejárat a Vajda János utca 1 felől)',
                'phone' => '+36-70-271-1524',
                'email' => 'robert.gere@gmail.com',
                'website' => 'https://shorturl.at/3VkWK',
                'image' => 'auto_klima_gumiszerviz.jpg',
                'rating' => 5,
                'opening_hours' => "hétfő 8:00–17:00\nkedd 8:00–17:00\nszerda 8:00–17:00\ncsütörtök 8:00–17:00\npéntek 8:00–17:00\nszombat 8:00–12:00\nvasárnap Zárva",
                'features' => 'Alufelni szerelés, centírozás, gumiabroncs kereskedés, klímaszerelés, klímatisztítás.',
                'lat' => 46.657927,
                'lng' => 21.285666,
                'long_desc' => 'Sarkad felől a legkönnyebben megközelíthető, korszerű gépparkkal rendelkező gumiabroncs szerviz.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'gumiszerviz',
                'slug' => Str::slug('rokszin-gumiszerviz'),
                'name' => 'Rokszin Gumiszerviz',
                'desc' => 'Autógumi vásárlás, szerelés, lemez- és alufelni árusítás rövid határidővel.',
                'address' => '5720, Sarkad, Szalontai út 9.',
                'phone' => '+36-70-7792-997',
                'email' => 'lacirokszin@gmail.com',
                'website' => 'https://shorturl.at/pyIQ3',
                'image' => 'rokszin.png',
                'rating' => 5,
                'opening_hours' => "hétfő 8:00–17:00\nkedd 8:00–17:00\nszerda 8:00–17:00\ncsütörtök 8:00–17:00\npéntek 8:00–17:00\nszombat 8:00–12:00\nvasárnap Zárva",
                'features' => 'Autógumi vásárlás, autógumi szerelés, lemez- és alufelnik árusítása.',
                'lat' => 46.746556,
                'lng' => 21.386656,
                'long_desc' => 'A szerviz fő profilja az autó- és motorgumik szerelése, javítása, valamint értékesítése. Az ügyfelek különösen dicsérik a gyors, pontos és korrekt kiszolgálást, valamint a barátságos árakat és a segítőkész, emberséges hozzáállást.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'gumiszerviz',
                'slug' => Str::slug('szabo-gumiszerviz'),
                'name' => 'Szabó Gumiszerviz',
                'desc' => 'Gyors gumiszerelés, javítás és 0-24 mobil gumiszerviz Békéscsabán.',
                'address' => '5600, Békéscsaba, Gyulai út 116.',
                'phone' => '+36-70-883-5700',
                'email' => 'szabogumikft@szabogumikft.hu',
                'website' => 'https://shorturl.at/c58SR',
                'image' => 'szabogumi.png',
                'rating' => 5,
                'opening_hours' => "hétfő 8:00–17:00\nkedd 8:00–17:00\nszerda 8:00–17:00\ncsütörtök 8:00–17:00\npéntek 8:00–17:00\nszombat 8:00–12:00\nvasárnap Zárva",
                'features' => 'Gumiszerelés, gumiabroncs javítás, kerékmosás, vulkanizálás, kerékkiegyensúlyozás, futómű beállítás, felni javítás, 0-24 mobil gumiszerviz.',
                'lat' => 46.678032,
                'lng' => 21.126837,
                'long_desc' => 'Ha Békéscsabán keresel megbízható és gyors gumiszervizt, a Szabó-Gumi Kft. ideális választás lehet számodra. A Gyulai út 116. szám alatt található vállalkozás több mint két évtizedes tapasztalattal rendelkezik, és széles körű szolgáltatásokat kínál: személyautók, teherjárművek, mezőgazdasági és ipari gépek gumiabroncsainak értékesítését, szerelését és javítását végzik.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'gumiszerviz',
                'slug' => Str::slug('pekarik-gumiszerviz-kft'),
                'name' => 'Pekárik Gumiszerviz Kft.',
                'desc' => 'Gumiabroncs szerviz és szalon Békéscsaba szívében, gyors és minőségi kiszolgálással.',
                'address' => '5600, Békéscsaba, Jókai u. 42.',
                'phone' => '+36-66-520-320',
                'email' => 'pekarik@pekarik.hu',
                'website' => 'https://shorturl.at/Sr1PI',
                'image' => 'pekarik.jpg',
                'rating' => 5,
                'opening_hours' => "hétfő 8:00–12:00, 13:00–17:00\nkedd 8:00–12:00, 13:00–17:00\nszerda 8:00–12:00, 13:00–17:00\ncsütörtök 8:00–12:00, 13:00–17:00\npéntek 8:00–12:00, 13:00–17:00\nszombat 8:00–12:00\nvasárnap Zárva",
                'features' => 'Gumiszerelés, kerékkiegyensúlyozás, keréktárcsa javítás, futóműállítás, gumiabroncstárolás, új és használt gumiabroncsok, új és használt alu illetve lemezkeréktárcsák, új és használt motorgumik.',
                'lat' => 46.680737,
                'lng' => 21.088133,
                'long_desc' => 'Az eltelt évek alatt nagyon sok igényt szolgáltunk ki - eredményességünk, magas színvonalú munkánk bizonyítéka elégedett és rendszeresen visszatérő ügyfeleink. Munkánk és árukészletünk színvonaláról győződjön meg személyesen Békéscsabán!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'gumiszerviz',
                'slug' => Str::slug('franko-gumicentrum-kft'),
                'name' => 'Frankó Gumicentrum Kft.',
                'desc' => 'Cégünk 1975 óta foglalkozik személy-, teher-, mezőgazdasági gumiabroncsok szerelésével. Békéscsabai és szarvasi telephelyeinken nagy raktárkészlettel várjuk kedves ügyfeleinket!',
                'address' => '5600, Békéscsaba, Madách utca 16/1.',
                'phone' => '+36-30-967-98-84',
                'email' => 'frankogumi@frankogumi.hu',
                'website' => 'https://shorturl.at/Bl18U',
                'image' => 'franko.jpeg',
                'rating' => 4.8,
                'opening_hours' => "hétfő 7:30–17:00\nkedd 7:30–17:00\nszerda 7:30–17:00\ncsütörtök 7:30–17:00\npéntek 7:30–17:00\nszombat 8:00–12:00\nvasárnap Zárva",
                'features' => 'Mezőgazdasági gép és teherautó gumiszerelés illetve javítás, gumijavítás, gumiszerelés, súlyzás kerék le- és felszerelés, mobil gumiszerelés, új gumiabroncs forgalmazása, gumitárolás.',
                'lat' => 46.663291,
                'lng' => 21.070580,
                'long_desc' => 'Napjainkban sajnos hiánycikk a megbízható, precíz iparos. Ez számunkra nagyon fontos a pozitív visszajelzés az általunk elvégzett munka színvonaláról. Ahogyan a régi mondás is tartja: az elégedett vevőnél nincs jobb reklám.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'gumiszerviz',
                'slug' => Str::slug('first-stop-gumi-es-futomuszerviz'),
                'name' => 'FIRST STOP Gumi és Futóműszerviz',
                'desc' => 'Békéscsaba belvárosában, könnyen elérhető és megbízható gumiszerviz!',
                'address' => '5600, Békéscsaba, Szarvasi út 14.',
                'phone' => '+36-30-635-8253',
                'email' => null,
                'website' => null,
                'image' => 'firststop.jpg',
                'rating' => 4.0,
                'opening_hours' => "hétfő 8:00–17:00\nkedd 8:00–17:00\nszerda 8:00–17:00\ncsütörtök 8:00–17:00\npéntek 8:00–17:00\nszombat 8:00–12:00\nvasárnap Zárva",
                'features' => 'Általános karbantartás, általános átvizsgálás, műszaki vizsgára felkészítés, akkumulátorjavítás és csere, izzócsere, fényszóró beállítás, fékjavítás, fékfolyadékcsere, futóműjavítás, lengéscsillapító-csere, váltójavítás, váltóolajcsere, vezérlés (szíj- vagy lánccsere), kuplungjavítás és csere, gumicsere, kipufogójavítás.',
                'lat' => 46.684087,
                'lng' => 21.087296,
                'long_desc' => 'Keress minket bizalommal, hiszen a fő profilunk mellett - amit a futóműbeállítás és gumiszerviz alkot - számos problémára tudunk megoldást nyújtani!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'gumiszerviz',
                'slug' => Str::slug('gumihangya-kft-gumiszerviz'),
                'name' => 'Gumihangya Kft. Gumiszerviz',
                'desc' => 'Ha nem szeretnél órákat várni egy egyszerű gumicserére, és inkább olyan helyet keresel, ahol gyorsaság, hozzáértés és korrektség alap, akkor a Gumihangya Kft.-nél a helyed!',
                'address' => '5624, Doboz, Nagy utca 12.',
                'phone' => '+36-66-268-678',
                'email' => 'dobozigumi@felnijavitas-doboz.hu',
                'website' => 'https://shorturl.at/vRfCS',
                'image' => null,
                'rating' => 4.6,
                'opening_hours' => "hétfő 7:30–17:00\nkedd 7:30–17:00\nszerda 7:30–17:00\ncsütörtök 7:30–17:00\npéntek 7:30–17:00\nszombat 7:30–12:00\nvasárnap Zárva",
                'features' => 'Autószerelés, gumiszerviz, felnijavítás.',
                'lat' => 46.732886,
                'lng' => 21.237714,
                'long_desc' => 'Ez a dobozi gumiszerviz nemcsak precíz és gyors munkát végez, hanem valóban figyel rád: segítenek kiválasztani a legjobb gumit, megjavítják a felnit, és közben barátságosan, korrektül bánnak veled.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automoso',
                'slug' => Str::slug('ccc-auto-kozmetika'),
                'name' => 'CCC Autókozmetika',
                'desc' => 'Autók külső-, belső takarítása, kárpittisztítás, polírozás, kerámia és bevonatok applikációja.',
                'address' => '5700, Gyula, Nagyváradi út 38.',
                'phone' => '+36-30-522-5531',
                'email' => null,
                'website' => 'https://shorturl.at/XALrJ',
                'image' => 'ccc_auto_kozmetika.jpg',
                'rating' => 3,
                'opening_hours' => "hétfő 12:00 – 18:00\nkedd 8:00 – 18:00\nszerda 8:00 – 18:00\ncsütörtök 8:00 – 18:00\npéntek 8:00 – 18:00\nszombat 8:00 – 18:00\nvasárnap Zárva",
                'features' => 'Prémium wax, belső és külső autótakarítás, gumiápolás, polírozás, kerámiabevonat.',
                'lat' => 46.649357,
                'lng' => 21.283692,
                'long_desc' => 'Ha igazán ragyogó, ápolt autót szeretnél, látogass el hozzánk és mi garantáljuk, hogy elégedetten távozol tiszta és ápolt külsejű és belsejű autóddal!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automoso',
                'slug' => Str::slug('judowash-auto-moso'),
                'name' => 'Judowash autómosó',
                'desc' => 'Non-stop nyitvatartással és profi gépekkel várjuk vendégeinket az ország 4 pontján, kötük Gyulán is.',
                'address' => '5700, Gyula, Csabai út 9.',
                'phone' => null,
                'email' => 'judowash@gmail.com',
                'website' => 'https://shorturl.at/XbZjS',
                'image' => 'judowash_auto_moso.jpg',
                'rating' => 4.5,
                'opening_hours' => '0-24',
                'features' => 'Aktív habos mosás, samponos mosás, foltmentes öblítés, bogároldó, kézi mosó.',
                'lat' => 46.643435,
                'lng' => 21.257621,
                'long_desc' => 'A város legforgalmasabb részén található mosóban mindig csillogós autók tömkelege látható, hiszen az aktív habnak köszönhetően ez könnyen elérhetővé válik bárki számára.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automoso',
                'slug' => Str::slug('pure-care-auto-kozmetika'),
                'name' => 'Pure Care Autókozmetika',
                'desc' => 'Szerettel várunk mindenkit, aki ragyogóan tiszta autót szeretne magának, de nincsen ideje otthon kitakarítani, illetve lemosni. Prémium tisztító és ápoló szereink kíméletesen teszik csillogóan tisztává gépjárművedet!',
                'address' => '5700, Gyula, Nürnbergi u. 10.',
                'phone' => '+36-20-310-8586',
                'email' => null,
                'website' => null,
                'image' => 'pure_care_auto_kozmetika.jpg',
                'rating' => 5,
                'opening_hours' => "hétfő 8:00–18:00\nKedd 8:00–18:00\nSzerda 8:00–18:00\nCsütörtök 8:00–18:00\nPéntek 8:00–18:00\nSzombat 9:00–14:00\nVasárnap Zárva",
                'features' => 'Autó külső és belső ápolása, wax, gumiápolás, kárpittisztítás.',
                'lat' => 46.650174,
                'lng' => 21.265941,
                'long_desc' => 'A Pure Care Autókozmetika a prémium autóápolás szakértője, ahol minden jármű különleges bánásmódban részesül. Célunk, hogy ügyfeleink autója ne csak tiszta legyen, hanem visszanyerje eredeti fényét és megjelenését. Szolgáltatásaink között megtalálható a külső-belső kézi autómosás, polírozás, kárpittisztítás, kerámia bevonat és fényezésvédelem is – mindezt professzionális eszközökkel és prémium minőségű anyagokkal végezzük.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automoso',
                'slug' => Str::slug('venus-auto-kozmetika'),
                'name' => 'VENUS Autókozmetika',
                'desc' => 'A Vénusz Autókozmetika gondoskodik arról, hogy autód mindig makulátlan és ápolt legyen. Szolgáltatásaink között megtalálható a kézi autómosás, belső tisztítás, viaszolás és karbantartó kozmetika – precízen, megbízhatóan, barátságos áron.',
                'address' => '5700, Gyula, Kálvária 3.',
                'phone' => '+36-20-350-8910',
                'email' => null,
                'website' => 'https://shorturl.at/rsjPE',
                'image' => 'venus_auto_kozmetika.jpg',
                'rating' => 5,
                'opening_hours' => "hétfő 8:00–16:00\nkedd 8:00–16:00\nszerda 8:00–16:00\ncsütörtök 8:00–16:00\npéntek 8:00–16:00\nszombat Zárva\nvasárnap Zárva",
                'features' => 'Ózonos fertőtlenítés, külső-belső tisztítás és ápolás, külső-belső műanyag elemek tisztítása, polírozás, kerámia, wax telepítés, fényszóró polírozás, üvegfelületek tisztítása, motortér tisztítás, felni tisztítás, ápolás.',
                'lat' => 46.635830,
                'lng' => 21.259117,
                'long_desc' => 'A Vénusz Autókozmetika olyan hely, ahol az autóápolás nem csak munka, hanem szenvedély. Célunk, hogy minden jármű tisztán, igényesen és újszerű állapotban térjen vissza tulajdonosához. Legyen szó egy gyors külső tisztításról vagy teljes belső-külső kozmetikáról, csapatunk precízen, odafigyeléssel dolgozik – mert hisszük, hogy a részletekben rejlik a minőség.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automoso',
                'slug' => Str::slug('kolener-car-studio'),
                'name' => 'Koléner Car Studio',
                'desc' => 'Ahol a precizitás és az autóápolás találkozik, ott mi vagyunk!',
                'address' => '5600, Békéscsaba, Orosházi út 88. (Tondach)',
                'phone' => '+36-70-421-9468',
                'email' => 'kolenercarstudio@gmail.com',
                'website' => 'https://shorturl.at/ruPDJ',
                'image' => 'kolener.png',
                'rating' => 5.0,
                'opening_hours' => "Minden nap előre egyeztetett időpont szükséges!\nhétfő 8:00-17:00\nkedd 8:00-17:00\nszerda 8:00-17:00\ncsütörtök 8:00-17:00\npéntek 8:00-17:00\nszombat Zárva\nvasárnap Zárva",
                'features' => 'Bőrfelület javítás és festés, karosszéria polírozás és kerámiabevonat, felni polírozás és kerámiabevonat, üveg polírozás, külső-belső kővédő fóliázás, belső takarítás.',
                'lat' => 46.663981,
                'lng' => 21.079039,
                'long_desc' => 'Minden szolgáltatásunk a legmagasabb minőségi standardok szerint készült, hogy biztosítsuk a legjobb eredményeket. A stúdió kizárólag prémium kategóriás anyagokkal és gépekkel dolgozik, és munkájukra garanciát vállalnak. A tulajdonos, Koléner Zoltán, személyesen felügyeli a munkálatokat, biztosítva a magas színvonalat és precizitást.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automoso',
                'slug' => Str::slug('onkiszolgalo-automoso'),
                'name' => 'Önkiszolgáló Autómosó',
                'desc' => 'Új tulajdonossal, megújult környezetben újra nyitott önkiszolgáló autómosónk a Csorvási út 8. szám alatt.',
                'address' => '5600, Békéscsaba, Csorvási út 8.',
                'phone' => '+36-70-425-9282',
                'email' => 'szekelyrobert@hotmail.com',
                'website' => 'https://shorturl.at/JoAOo',
                'image' => 'onkiszolgalo-automoso.jpg',
                'rating' => 5.0,
                'opening_hours' => '0-24',
                'features' => 'Időzített programok, bankkártyás fizetés, környezetbarát tisztítószerek, ingyenes porszívóhasználat, minőség megfizethető áron.',
                'lat' => 46.681294,
                'lng' => 21.055139,
                'long_desc' => 'Többféle program közül választhat, hogy az Ön igényeinek leginkább megfelelő tisztítást végezhesse el. Mindezt környezetbarát tisztítószerekkel, amelyek kíméletesek az autóval és a környezettel egyaránt. Jöjjön el hozzánk, ha szeretné felfrissíteni járművét!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automoso',
                'slug' => Str::slug('csaszi-autokozmetika'),
                'name' => 'Csaszi Autókozmetika',
                'desc' => 'Ha olyan helyet keresel Békéscsabán, ahol az autódat nemcsak megtisztítják, hanem valóban újjávarázsolják.',
                'address' => '5600, Békéscsaba, Szarvasi út 28/1.',
                'phone' => '+36-70-677-2199',
                'email' => 'csasziautokozmetika@gmail.com',
                'website' => 'https://shorturl.at/ldp0D',
                'image' => 'csaszi.png',
                'rating' => 4.7,
                'opening_hours' => "hétfő: 8:00–18:00\nkedd: 8:00–18:00 \nszerda: 8:00–18:00 \ncsütörtök: 8:00–18:00 \npéntek 8:00–18:00,\nszombat 8:00–14:00, \nvasárnap Zárva",
                'features' => 'Belső-külső tisztítás, ózonos tisztítás, kárpit tisztítás, felni tisztítás, gumiápolás, bőrápolás.',
                'lat' => 46.683437,
                'lng' => 21.083984,
                'long_desc' => 'A Szarvasi út 28/1. szám alatt található műhelyben a részletekre való odafigyelés és a precíz munka alapérték! Itt az autódat nemcsak megtisztítják, hanem valóban újjávarázsolják.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automoso',
                'slug' => Str::slug('fortenza-auto-detailing-studio'),
                'name' => 'Fortenza Auto Detailing Studio',
                'desc' => 'Prémium minőség megfizethető áron? Nem mellesleg végeredményként egy patyolat tiszta autó kívül-belül?',
                'address' => '5600, Békéscsaba, Bartók Béla út 70.',
                'phone' => '+36-30-820-4904',
                'email' => 'fortenzaa@gmail.com',
                'website' => 'https://www.facebook.com/fortenza',
                'image' => 'fortenza.png',
                'rating' => 5.0,
                'opening_hours' => "hétfő Zárva\nkedd: 9:00–19:00 \nszerda: 9:00–19:00 \ncsütörtök: 9:00–19:00 \npéntek: 9:00–19:00 \nszombat 9:00–19:00 \nvasárnap Zárva",
                'features' => 'Autóápolás, kerámia bevonat, polírozás, prémium szolgáltatások.',
                'lat' => null,
                'lng' => null,
                'long_desc' => 'Ha egy részletes autóápolásra szeretnéd vinni szeretett autódat, nyugodtan bízd Ránk, hiszen prémium anyaghasználatunk és eszközeink sérülésmentes ápolást tesznek lehetővé. Őrizd meg autód fényezésének épségét, polírozást is kérhetsz extra fényességért!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automoso',
                'slug' => Str::slug('royal-garage-autokozmetika'),
                'name' => 'Royal Garage Autókozmetika',
                'desc' => 'Ha azt szeretnéd, hogy autód ne csak tiszta, hanem valóban újszerű legyen, a Royal Garage Autókozmetika a tökéletes választás számodra.',
                'address' => '5720, Sarkad, Márky Sándor utca 44.',
                'phone' => '+36-30-889-8624',
                'email' => 'royalgarageautokozmetika@gmail.com',
                'website' => 'https://shorturl.at/zMAHN',
                'image' => 'royalgarage.jpeg',
                'rating' => 4.7,
                'opening_hours' => "Hétfő 8:00–17:00\nKedd 8:00–17:00\nSzerda 8:00–17:00\nCsütörtök 8:00–17:00\nPéntek 8:00–17:00\nSzombat 8:00–17:00\nVasárnap Zárva",
                'features' => 'Külső tisztítás, felni és gumi tisztítás, üveg felületek tisztítása, dekontaminálás, waxolás, belső tisztítás, porszívózás, kárpittisztítás, műanyag felületek tisztítása és ápolása, ózon fertőtlenítés.',
                'lat' => 46.733535,
                'lng' => 21.384474,
                'long_desc' => 'A Royal Garage Autókozmetika széles körű autóápolási szolgáltatásokat kínál, beleértve a külső-belső tisztítást, kárpittisztítást, és ózonos fertőtlenítést is. Munkájukat prémium minőségű anyagokkal és eszközökkel végzik, hogy az autó valóban újszerűvé váljon.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automentok',
                'slug' => Str::slug('automento-gyula'),
                'name' => 'Autómentő Gyula',
                'desc' => 'Legyen szó egy lerobbant gépjárműről, mi mindig rendelkezésedre állunk!',
                'address' => '5700, Gyula, Nagyfenék 37.',
                'phone' => '+36-20-358-6113',
                'email' => 'automento.gyula@gmail.com',
                'website' => 'https://shorturl.at/CqPnY',
                'image' => 'hajdu_lajos_automento.jpg',
                'rating' => 5.0,
                'opening_hours' => "Éjjel-nappal 0-24 hívható",
                'features' => 'Autómentés, gépszállítás, darus autómentés, daruzás, műszaki mentés.',
                'lat' => 46.685650,
                'lng' => 21.269330,
                'long_desc' => 'A Gyulai Autómentő gyors és megbízható segítséget nyújt a nap 24 órájában, legyen szó műszaki hibáról vagy balesetről. Korszerű járműveikkel biztonságosan szállítják el autóját, akár azonnali indulással is, Gyulán és környékén.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automentok',
                'slug' => Str::slug('car-potlas-automento'),
                'name' => 'Car-Pótlás Autóbontó-autómentés',
                'desc' => '3,5 tonna önsúlyig éjjel-nappal, bel- és külföldről is vállaljuk autók szállítását.',
                'address' => '5700, Gyula, 44-es főút, 134.km',
                'phone' => '+36-30-638-8398',
                'email' => 'matyitomi@yahoo.com',
                'website' => 'https://shorturl.at/kGBp2',
                'image' => 'car-potlas.jpg',
                'rating' => 4.6,
                'opening_hours' => "Éjjel-nappal 0-24 hívható",
                'features' => 'Autómentés, autóbontás, alkatrészkereskedelem, gépszállítás.',
                'lat' => 46.653616,
                'lng' => 21.230711,
                'long_desc' => 'Gyulán és környékén nyújt gyors, megbízható segítséget 0–24 órában. Hidroplatós járműveikkel akár 3,5 tonnáig vállalnak mentést, baleset vagy meghibásodás esetén is, több évtizedes tapasztalattal.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automentok',
                'slug' => Str::slug('hajdu-lajos-automento'),
                'name' => 'Hajdu Lajos Ev.',
                'desc' => 'Egész nap rendelkezésre álló autómentő szolgáltatás Gyulán, akár tehergépkocsi számára is.',
                'address' => '5700, Gyula, Pap u. 4.',
                'phone' => '+36-30-945-1942',
                'email' => 'automentes@t-email.hu',
                'website' => null,
                'image' => null,
                'rating' => 4.7,
                'opening_hours' => "Éjjel-nappal 0-24 hívható",
                'features' => 'Autómentés, autószállítás, darus autómentő, gumi szerviz, kamionmentés.',
                'lat' => 46.642741,
                'lng' => 21.260858,
                'long_desc' => 'Egész nap rendelkezésre álló autómentő szolgáltatás Gyulán, akár tehergépkocsi számára is, legyen szó balesetről vagy szimpla műszaki hibáról. Mobil gumiszervizként is hívható!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automentok',
                'slug' => Str::slug('automento-bekescsaba'),
                'name' => 'Autómentő Békéscsaba',
                'desc' => 'NON STOP autómentés-kamionmentés, műszaki mentés és gépszállítás Magyarország és teljes Európa területén.',
                'address' => '5600, Békéscsaba, Kisrét tanya 96.',
                'phone' => '+36-21-252-0453',
                'email' => 'automento74@gmail.com',
                'website' => 'https://shorturl.at/zzVIt',
                'image' => 'automentobekescsaba.png',
                'rating' => 5.0,
                'opening_hours' => "Éjjel-nappal 0-24 hívható",
                'features' => 'Személyautó mentés, lakókocsi és lakóautó mentés, utánfutó mentés, motorkerékpár mentés, haszongépjármű mentés, mezőgazdasági gép mentés és szállítás, rakodógép, munkagép mentés, szállítás, építőipari gép mentés, szállítás, targonca szállítás, egyéb munkagépek és eszközök mentése, szállítása.',
                'lat' => 46.707093,
                'lng' => 21.059352,
                'long_desc' => 'A műszaki mentés, gépszállítás mellett segítünk műszaki hibás gépjárműve S.O.S. szervizelésében is. Igény esetén csereautót biztosítunk ügyfeleink számára.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automentok',
                'slug' => Str::slug('mate-fuvar-auto-mento'),
                'name' => 'Máté Fuvar - Autómentő',
                'desc' => 'Mottónk a megbízhatóság, gyorsaság, precizitás, melyet elégedett ügyfeleink növekvő száma igazol.',
                'address' => '5600, Békéscsaba, Corvin u. 19.',
                'phone' => '+36-30-242-7000',
                'email' => 'matefuvar@matefuvar.hu',
                'website' => 'https://shorturl.at/W3Uwl',
                'image' => 'matefuvar.jpeg',
                'rating' => 5.0,
                'opening_hours' => "Éjjel-nappal 0-24 hívható",
                'features' => 'Autómentés, áruszállítás, költöztetés.',
                'lat' => 46.671095,
                'lng' => 21.106035,
                'long_desc' => 'Cégünk fő profilja az autómentés. Békés megye és vonzáskörzetében harmadik generáció óta végezzük autómentő tevékenységünket.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automentok',
                'slug' => Str::slug('lukacs-auto-mentes'),
                'name' => 'Lukács Autómentés',
                'desc' => 'Azonnali indulással és gyors segítségnyújtással sietünk problémás autódért Békéscsabán és környékén!',
                'address' => '5600, Békéscsaba, Felsőnyomás u. 197.',
                'phone' => '+36-20-370-7155',
                'email' => 'lukacsautomentes@gmail.com',
                'website' => 'https://shorturl.at/04XS7',
                'image' => 'lukacs.jpeg',
                'rating' => 4.7,
                'opening_hours' => "Éjjel-nappal 0-24 hívható",
                'features' => 'Autómentés, gépszállítás, daruzás, raklapos áru szállítás, szálanyag szállítás.',
                'lat' => 46.702967,
                'lng' => 21.057446,
                'long_desc' => 'A Lukács Autómentő csapata tapasztalt szakemberekből áll, akik a nap 24 órájában készen állnak arra, hogy segítsenek a bajba jutott autósoknak. A vállalkozás célja, hogy ügyfeleik gyorsan és biztonságosan jussanak el a kívánt helyszínre, miközben járművük a legjobb kezekben van.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automentok',
                'slug' => Str::slug('muranyi-mentes'),
                'name' => 'Murányi Mentés - Autómentés, Gépszállítás',
                'desc' => 'Percek alatt odaérünk érted Békéscsabán, azonban ha a környező városokban vagy sem kell aggódnod, hamar odaérünk és elhárítjuk a problémát vagy elszállítjuk meghibásodott járművedet!',
                'address' => '5600, Békéscsaba, Kerek Tanya 906.',
                'phone' => '+36-30-510-9959',
                'email' => null,
                'website' => 'https://shorturl.at/vQf0D',
                'image' => 'muranyi.png',
                'rating' => 5.0,
                'opening_hours' => "Éjjel-nappal 0-24 hívható",
                'features' => 'Autómentés, gépszállítás, hajószállítás, vízre telepítés, baleseti mentés.',
                'lat' => 46.645236,
                'lng' => 21.069373,
                'long_desc' => 'A Murányi Mentés tapasztalt csapata készen áll arra, hogy segítsen a legnehezebb helyzetekben is, legyen szó balesetről vagy műszaki hibáról. Ha gyors és professzionális segítségre van szükséged, ne habozz felvenni velük a kapcsolatot!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
