<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ServicesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('services')->insert([
            [
                'type' => 'alkatreszkereskedo',
                'slug' => Str::slug('bardi-auto-gyula'),
                'name' => 'Bárdi Autó Gyula',
                'desc' => 'A Bárdi Autó Magyarország egyik legjelentősebb autóalkatrész-kereskedelmi vállalata.',
                'address' => '5700, Gyula, Kétegyházi út 1/a.',
                'phone' => '+36-1-555-0050',
                'email' => 'vevoszolgalat@bardiauto.hu',
                'website' => 'https://www.bardiauto.hu/webshop/',
                'image' => 'bardi-auto.png',
                'rating' => 4.6,
                'opening_hours' => "hétfő 7:30–17:30\nkedd 7:30–17:30\nszerda 7:30–17:30\ncsütörtök 7:30–17:30\npéntek 7:30–17:30\nszombat 8:00–13:00\nvasárnap Zárva",
                'features' => 'Alvázszám kereső, személygépjármű, illetve haszongépjármű alkatrészek, motorkerékpár alkatrészek, cikkszámkereső, olajok, folyadékok, autóápolási cikkek, kiegészítők.',
                'lat' => 46.639982,
                'lng' => 21.262126,
                'long_desc' => 'Jelen vagyunk Romániában és Szlovákiában is, saját tulajdonú kirendeltségekkel. Büszkék vagyunk arra, hogy kínálatunk a kelet-európai régióban kiemelkedő módon minden igényt lefed. Központi raktárkészletünk több mint 4 millió árucikkből áll. Egyaránt árulunk alkatrészeket és felszerelési cikkeket személy-, és tehergépjárművekhez, motorkerékpárokhoz. Választékunkban a garázsipari berendezések széles választéka is elérhető. Kirendeltségeinken és webáruházunkban szakértő tanácsadással viszonteladó partnereinket és magánszemélyeket is kiszolgálunk.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'alkatreszkereskedo',
                'slug' => Str::slug('unix-gyula'),
                'name' => 'UNIX Gyula',
                'desc' => 'Az UNIX Autó Kft. Magyarország piacvezető autóalkatrész- kereskedelmi vállalata.',
                'address' => '5700, Gyula, Csabai út 9.',
                'phone' => '+36-1-270-8701',
                'email' => 'info@unixauto.hu',
                'website' => 'https://www.unixauto.hu',
                'image' => 'unix-auto.jpg',
                'rating' => 4.4,
                'opening_hours' => "hétfő 7:30–17:30\nkedd 7:30–17:30\nszerda 7:30–17:30\ncsütörtök 7:30–17:30\npéntek 7:30–17:30\nszombat 8:00–13:00\nvasárnap Zárva",
                'features' => 'Szakmai oktatások partnereink részére, célszerszámbérlési lehetőség, gyári alkatrész ajánlatkérő rendszer, fáradt olaj és olajos veszélyes hulladék kezelési lehetőség, laboratóriumi kenőanyagelemzés, szervizinformációs szoftverek, diagnosztikai termékek.',
                'lat' => 46.643773,
                'lng' => 21.257114,
                'long_desc' => 'A hazai piac mellett jelen vagyunk Romániában és Szlovákiában is. Több, mint 500 beszállítóval állunk kapcsolatban és 10 millió darabos raktárkészletünket kirendeltségeinken, viszonteladóinknál és szervizeinkben is eléred. Magyarországon, Romániában és Szlovákiában közel 170 kirendeltségben várunk.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'alkatreszkereskedo',
                'slug' => Str::slug('olah-autoalkatresz-kis-es-nagyker'),
                'name' => 'Oláh Autóalkatrész kis- és nagyker',
                'desc' => 'Autóalkatrész kis- és nagykereskedés hálózat az ország több pontján.',
                'address' => '5700, Gyula, Nagyváradi út 10.',
                'phone' => '+36-20-61-61-100',
                'email' => 'oft@olahauto.hu',
                'website' => 'https://www.olahauto.hu',
                'image' => 'olah-auto.jpg',
                'rating' => 4.8,
                'opening_hours' => "hétfő 8:00–17:00\nkedd 8:00–17:00\nszerda 8:00–17:00\ncsütörtök 8:00–17:00\npéntek 8:00–17:00\nszombat Zárva\nvasárnap Zárva",
                'features' => 'Gépjármű gyorsszervíz, autóalkatrész kereskedés, ioncserélt víz csomagolás, gumiharang.',
                'lat' => 46.648128,
                'lng' => 21.284301,
                'long_desc' => '35 éves üzleti tapasztalatnak és pénzügyi stabilitásnak köszönhetõen jelenleg Békés megyében 4 üzletben várjuk vásárlóinkat, melyeket 4000 m2-es gyulai központi raktárbázisunkból látunk el. Budapesten logisztikai telephellyel rendelkezünk. A külkereskedelem liberalizációja óta export-import tevékenységet folytatunk, fõbb partnereink Ukrajnában, Litvániában, Bulgáriában, Kínában, Tajvanon és az Európai Unión belül találhatók.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'alkatreszkereskedo',
                'slug' => Str::slug('po-alkatresz-kft'),
                'name' => 'P.O. Alkatrész Kft.',
                'desc' => 'A 2009 óta működő cégünk személygépkocsi és kisteherautó alkatrészek kis- és nagykereskedelmével foglalkozik.',
                'address' => '5700 Gyula, Szent István u. 25/b.',
                'phone' => '+36-66-633-888',
                'email' => 'poauto@poauto.hu',
                'website' => 'https://poauto.hu',
                'image' => 'po-auto.png',
                'rating' => 5.0,
                'opening_hours' => "hétfő 8:00–17:00\nkedd 8:00–17:00\nszerda 8:00–17:00\ncsütörtök 8:00–17:00\npéntek 8:00–17:00\nszombat 09:00–12:00\nvasárnap Zárva",
                'features' => 'Motor kopóalkatrészek, autóalkatrészek.',
                'lat' => 46.640491,
                'lng' => 21.274444,
                'long_desc' => 'A P.O üzletében Ön elérhető áron vásárolhatja meg a kiváló minőségű alkatrészeket: után gyártott esetében raktárkészletünkből, illetve 1 napos beszerzési határidővel, de gyári alkatrészeket is beszerzünk Önnek rövid teljesítési idővel. Ezen felül vállaljuk a megrendelt alkatrészek postai úton történő elszállítását is.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'alkatreszkereskedo',
                'slug' => Str::slug('car-potlas-autobonto'),
                'name' => 'Car-Pótlás Autóbontó',
                'desc' => 'Jelenleg több mint 20.000 m2-es területen tevékenykedünk.',
                'address' => '5700, Gyula, 44-es főút, 134.km',
                'phone' => '+36-30-638-8398',
                'email' => 'matyitomi@yahoo.com',
                'website' => 'http://www.carpotlas.hu/index.php',
                'image' => 'car-potlas.jpg',
                'rating' => 4.6,
                'opening_hours' => "hétfő 7:30–12:00, 12:30–16:00\nkedd 7:30–12:00, 12:30–16:00\nszerda 7:30–12:00, 12:30–16:00\ncsütörtök 7:30–12:00, 12:30–16:00\npéntek Zárva\nszombat Zárva\nvasárnap Zárva",
                'features' => 'Autómentés, autóbontás, alkatrészkereskedelem, gépszállítás.',
                'lat' => 46.653616,
                'lng' => 21.230711,
                'long_desc' => 'A használt alkatrészeket megfelelő minősítéssel, a beépíthetőnek minősítetteket beszerelési garanciával, - igény szerint akár beszerelve-, kedvező áron kínáljuk a tisztelt ügyfelek részére. Törzsvásárlóinknak, szerelőknek, illetve nagyobb tételben vásárlóknak jelentős kedvezményeket biztosítunk!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'autoszerelo',
                'slug' => Str::slug('somogyi-autoszerelo-muhely'),
                'name' => 'Somogyi Autószerelő Műhely',
                'desc' => 'Folyamatosan biztosítjuk a műhelyünkben a személygépkocsik és tehergépjárművek szervizelését, karbantartását, műszaki vizsgáztatását.',
                'address' => '5700, Gyula, Cinka Panna u. 19-21.',
                'phone' => '+36-30-501-2247',
                'email' => 'somogyiautoszervizplusz@gmail.com',
                'website' => 'https://www.facebook.com/profile.php?id=100057107933613&locale=hu_HU',
                'image' => null,
                'rating' => 4.5,
                'opening_hours' => "hétfő 8:00–17:00\nkedd 8:00–17:00\nszerda 8:00–17:00\ncsütörtök 8:00–17:00\npéntek 8:00–17:00\nszombat Zárva\nvasárnap Zárva",
                'features' => 'Autóvillamosság, autóelektronika szerelés, műszaki vizsgára felkészítés, autószerelés, állapotfelmérés, motordiagnosztika, olajcsere, fékrendszerek speciális javítása.',
                'lat' => 46.638124,
                'lng' => 21.269983,
                'long_desc' => 'A műhely munkatársai rendkívül segítőkészek, gyorsak és precízek, gyakran túllépve az elvárható szinten. Számos ügyfél kiemelte a korrekt kommunikációt, a tájékoztatás minőségét és a váratlan helyzetekben nyújtott segítséget. A műhely vezetője és csapata nemcsak szakmailag kiváló, hanem emberségük és kedvességük miatt is kiemelkedő. Az ügyfelek többsége szívből ajánlja a műhelyt, különösen azoknak, akik kiváló szakemberekre és megbízható szolgáltatásra vágynak.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'autoszerelo',
                'slug' => Str::slug('gamma-autoszerviz-es-autokozmetika'),
                'name' => 'Gamma Autószerviz & Autókozmetika',
                'desc' => 'A Gamma Autószerviz továbbra is várja meglévő és leendő ügyfeleit!',
                'address' => '5700, Gyula, Csabai út 135.',
                'phone' => '+36-30-725-4899',
                'email' => 'service@gammatrans.hu',
                'website' => 'https://www.facebook.com/gammaautoszerviz/?locale=hu_HU',
                'image' => 'gamma-autoszerviz.jpg',
                'rating' => 4.8,
                'opening_hours' => "hétfő 8:00–17:00\nkedd 8:00–17:00\nszerda 8:00–17:00\ncsütörtök 8:00–17:00\npéntek 8:00–17:00\nszombat Zárva\nvasárnap Zárva",
                'features' => 'Autószerelés szolgáltatás, autóbróker, autótakarítás és mosás.',
                'lat' => 46.651826,
                'lng' => 21.245019,
                'long_desc' => 'Megfelelő választás, ha eladásra kerül a sor, viszont ha egy szerelés vár az autódra, azt is megoldhatod itt.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'autoszerelo',
                'slug' => Str::slug('lengyel-autoszerviz'),
                'name' => 'Lengyel Autószerviz',
                'desc' => 'Tökéletes választás egy műszaki vizsga előtti átnézésre, esetleges javításra Gyulán!',
                'address' => '5700, Gyula, Dobozi út 28.',
                'phone' => '+36-30-958-9429',
                'email' => 'kipufogoszakszerviz@t-online.hu',
                'website' => 'http://www.kipufogoszakszerviz.hu/?fbclid=IwY2xjawKG2rFleHRuA2FlbQIxMABicmlkETBqV1R2UEtUeDFrOEtqcWQ1AR6U82WX1FDG1GYqOC27EXQ48NmZ8cJFK8YZKe1tlKzkZYJ50YEqNsQPXg_bEw_aem_kUuOP0btkQ9MZCkuPGHZEw',
                'image' => 'lengyel-autoszerviz.jpg',
                'rating' => 4.6,
                'opening_hours' => "hétfő 8:00–17:00\nkedd 8:00–17:00\nszerda 8:00–17:00\ncsütörtök 8:00–17:00\npéntek 8:00–17:00\nszombat Zárva\nvasárnap Zárva",
                'features' => 'Márkafüggetlen gépjárműjavítás (futó és nagyjavítások), gumiszerelés, futómű javítás és állítás, diagnosztika, lakatos munkák, kipufogó katalizátor javítás és csere.',
                'lat' => 46.661256,
                'lng' => 21.277925,
                'long_desc' => 'A munka megkezdése előtt minden esetben megbeszéljük Önnel a szükséges munkálatokat. Szakképzett csapatunk mindent megtesz az Ön autójáért. Mindig gyorsan és az igényeinek megfelelően tesszük a dolgunkat. Számunkra mindig fontos szempont a magas színvonalú szolgáltatás versenyképes áron.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'autoszerelo',
                'slug' => Str::slug('kempf-auto'),
                'name' => 'Kempf Autó',
                'desc' => 'Megbízható Bosch szervíz, illetve vizsgaközpont, ahol egészen 3,5 T súlyig minden jármű megfordul!',
                'address' => '5700, Gyula, Kétegyházi út 8.',
                'phone' => '+36-70-457-5700',
                'email' => 'info@kempf.hu',
                'website' => 'https://www.facebook.com/kempfauto/',
                'image' => 'kempf-auto.jpg',
                'rating' => 4.6,
                'opening_hours' => "hétfő 8:00–17:00\nkedd 8:00–17:00\nszerda 8:00–17:00\ncsütörtök 8:00–17:00\npéntek 8:00–17:00\nszombat Zárva\nvasárnap Zárva",
                'features' => 'Általános szervizelés, műszaki vizsgáztatás, eredetiség vizsgálat, autóvillamosság, gumi szerelés/javítás, futómű állítás/javítás, fék szerviz, autódiagnosztika.',
                'lat' => 46.632934,
                'lng' => 21.258109,
                'long_desc' => 'Szerelőink gőz erővel dolgoznak nap, mint nap azon, hogy a hasonló életmentő műtéteket precízen és szakszerűen elvégezzék az Ügyfeleink autóin!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'gumiszerviz',
                'slug' => Str::slug('gyulai-gumiszerviz-kft'),
                'name' => 'Gyulai Gumiszerviz Kft.',
                'desc' => 'Cégünk gyorsan és rugalmasan reagál bármilyen egyedi megrendelés esetén is. Tervezzük az eszközpark fejlesztését a fokozott minőségi elvárások érdekében.',
                'address' => '5700, Gyula, Bicere 14/a.',
                'phone' => '+36 20 345 7150',
                'email' => 'info@gyulaigumiszerviz.hu',
                'website' => 'http://www.gyulaigumiszerviz.hu/',
                'image' => 'gyulai-gumiszerviz.jpg',
                'rating' => 4.8,
                'opening_hours' => "hétfő 8:00–16:00\nkedd 8:00–16:00\nszerda 8:00–16:00\ncsütörtök 8:00–16:00\npéntek 8:00–16:00\nszombat 8:00–12:00\nvasárnap Zárva",
                'features' => 'Személygépkocsi, teherautó, kamion, motor és kerékpár, haszongépjármű gumiabroncsok forgalmazása, gumiabroncsok javítása, szerelés, centrírozás, keréktárolás, szaktanácsadás.',
                'lat' => 46.654945,
                'lng' => 21.237890,
                'long_desc' => '2013 őszén vállalkozásunk megnyitotta Gumiszerviz részlegét, ahol igyekszünk szintén teljes körű szolgáltatást nyújtani. Tevékenységi körünkbe tartozik többek között személygépkocsi, teherautó, kamion, motor és kerékpár, haszongépjármű gumiabroncsok forgalmazása, javítása, szerelése, centírozása.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'gumiszerviz',
                'slug' => Str::slug('pneubox-kft'),
                'name' => 'PNEUBOX Kft.',
                'desc' => 'Cégünk 2005-ben alakult fő profilunk a gumiabroncsok kereskedelme, szerelése és javítása. 2013 óta megújult környezetben várjuk kedves ügyfeleinket.',
                'address' => '5700, Gyula, Kétegyházi út 7/a.',
                'phone' => '+36-30-325-97-97',
                'email' => 'pneuboxkft@gmail.com',
                'website' => 'http://pneuboxgumiszerviz.hu/',
                'image' => 'pneubox.jpg',
                'rating' => 5,
                'opening_hours' => "hétfő 7:30-17:00\nkedd 7:30-17:00\nszerda 7:30-17:00\ncsütörtök 7:30-17:00\npéntek 7:30-17:00\nszombat 8:00-12:00\nvasárnap Zárva\nebédszünet 12:00-12:30",
                'features' => 'Gumiszerelés, gumijavítás, keréktárcsa javítás, új és használt gumiabroncsok, tömlők, gumiabroncs tárolás.',
                'lat' => 46.634353,
                'lng' => 21.258005,
                'long_desc' => 'Szervizünk felszereltsége és szakembereink képzettsége révén minden egyes ügyfelünket maximális szakértelemmel szolgáljuk ki. Minőségi szolgáltatást nyújtunk a legmodernebb gépekkel és minőségi anyagokkal. A gumijavítást tapasztalt szakembereink gyorsan és megbízhatóan végzik el. A felhasznált anyagok kimagasló minősége és a csúcstechnológiás gépek alkalmazása ugyancsak az ügyfeleink biztonságát szolgálják.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'gumiszerviz',
                'slug' => Str::slug('kolus-trade-kft'),
                'name' => 'KÖLÜS-TRADE Kft.',
                'desc' => 'Hatalmas gumiválasztékkal vár a Gyulaváriban található, könnyen megközelíthető szervizkomplexum!',
                'address' => '5711, Gyula Temesvári út 69.',
                'phone' => '+36-20-3993-100',
                'email' => 'info@kolustrade.hu',
                'website' => 'https://kolustrade.hu/autogumi/',
                'image' => 'kolustrade.png',
                'rating' => 4.7,
                'opening_hours' => "hétfő 8.00-17.00\nkedd 8.00-17.00\nszerda 8.00-17.00\ncsütörtök 8.00-17.00\npéntek 8.00-17.00\nszombat 8.00-12.00\nvasárnap Zárva",
                'features' => 'Kerékpár értékesítés, kerti kisgépek, gumiabroncsok cseréje és szervizelése, munkagépek abroncsainak forgalmazása és cseréje.',
                'lat' => 46.635741,
                'lng' => 21.298369,
                'long_desc' => 'Ha azonnali gumicserére van szükséged, itt megoldják a problémáid! Korszerű gépek és munkaeszközök segítségével, egy pörgős csapat várja a kedves leendő, illetve már meglévő vendégeket!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'gumiszerviz',
                'slug' => Str::slug('filo-gumiszerviz'),
                'name' => 'Filó Gumiszerviz',
                'desc' => 'Könnyen elérhető, nagy raktárkészlettel rendelkező gumiszerviz Gyula belvárosában.',
                'address' => '5700, Gyula, Csabai út 40.',
                'phone' => '+36-20-957-2406',
                'email' => 'filobt@t-online.hu',
                'website' => 'https://www.nyitvatartas24.hu/uzlet/Gyula-Fil%25C3%25B3%2520Gumiszerviz%2520Bt.-378573L.html',
                'image' => 'filo.jpg',
                'rating' => 5,
                'opening_hours' => "hétfő 08:00-17:00\nkedd 08:00-17:00\nszerda 08:00-17:00\ncsütörtök 08:00-17:00\npéntek 08:00-17:00\nszombat 09:00-12:00\nvasárnap Zárva",
                'features' => 'Alufelni szerelés, centírozás, gumiabroncs kereskedés.',
                'lat' => 46.644114,
                'lng' => 21.257243,
                'long_desc' => 'A városba vezető utcán található gumiszervizben szakemberek végzik a munkát, ezzel minőséget biztosítva ügyfeleiknek.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'gumiszerviz',
                'slug' => Str::slug('auto-klima-es-gumiabroncs-szerviz'),
                'name' => 'Autóklíma és Gumiabroncs Szervíz',
                'desc' => 'Akár szezonális gumicsere vagy defekt miatt érkezel, itt hamar és pénztárcabarát módon juthatsz új abrocsaidhoz! Sőt, még a klímádat is kitisztíttathatod, hiszen itt ezzel is foglalkoznak!',
                'address' => '5700, Gyula, Sarkadi út 5. (bejárat a Vajda János utca 1 felől)',
                'phone' => '+36-70-271-1524',
                'email' => 'robert.gere@gmail.com',
                'website' => 'https://www.facebook.com/p/Autóklíma-és-Gumiabroncs-Szervíz-Gyula-100077915514796/?locale=hu_HU',
                'image' => 'auto_klima_gumiszerviz.jpg',
                'rating' => 5,
                'opening_hours' => "hétfő 8:00–17:00\nkedd 8:00–17:00\nszerda 8:00–17:00\ncsütörtök 8:00–17:00\npéntek 8:00–17:00\nszombat 8:00–12:00\nvasárnap Zárva",
                'features' => 'Alufelni szerelés, centírozás, gumiabroncs kereskedés, klímaszerelés, klímatisztítás.',
                'lat' => 46.657927,
                'lng' => 21.285666,
                'long_desc' => 'Sarkad felől a legkönnyebben megközelíthető, korszerű gépparkkal rendelkező gumiabroncs szerviz.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automoso',
                'slug' => Str::slug('ccc-auto-kozmetika'),
                'name' => 'CCC Autókozmetika',
                'desc' => 'Autók külső-, belső takarítása, kárpittisztítás, polírozás, kerámia és bevonatok applikációja.',
                'address' => '5700, Gyula, Nagyváradi út 38.',
                'phone' => '+36-30-522-5531',
                'email' => null,
                'website' => 'https://www.facebook.com/autokozmetikagyula/?locale=hu_HU',
                'image' => 'ccc_auto_kozmetika.jpg',
                'rating' => 3,
                'opening_hours' => "hétfő 12:00 – 18:00\nkedd 8:00 – 18:00\nszerda 8:00 – 18:00\ncsütörtök 8:00 – 18:00\npéntek 8:00 – 18:00\nszombat 8:00 – 18:00\nvasárnap Zárva",
                'features' => 'Prémium wax, belső és külső autótakarítás, gumiápolás, polírozás, kerámiabevonat.',
                'lat' => 46.649357,
                'lng' => 21.283692,
                'long_desc' => 'Ha igazán ragyogó, ápolt autót szeretnél, látogass el hozzánk és mi garantáljuk, hogy elégedetten távozol tiszta és ápolt külsejű és belsejű autóddal!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automoso',
                'slug' => Str::slug('judowash-auto-moso'),
                'name' => 'Judowash autómosó',
                'desc' => 'Non-stop nyitvatartással és profi gépekkel várjuk vendégeinket az ország 4 pontján, kötük Gyulán is.',
                'address' => '5700, Gyula, Csabai út 9.',
                'phone' => null,
                'email' => 'judowash@gmail.com',
                'website' => 'https://www.facebook.com/Judowash?locale=hu_HU',
                'image' => 'judowash_auto_moso.jpg',
                'rating' => 4.5,
                'opening_hours' => '0-24',
                'features' => 'Aktív habos mosás, samponos mosás, foltmentes öblítés, bogároldó, kézi mosó.',
                'lat' => 46.643435,
                'lng' => 21.257621,
                'long_desc' => 'A város legforgalmasabb részén található mosóban mindig csillogós autók tömkelege látható, hiszen az aktív habnak köszönhetően ez könnyen elérhetővé válik bárki számára.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automoso',
                'slug' => Str::slug('pure-care-auto-kozmetika'),
                'name' => 'Pure Care Autókozmetika',
                'desc' => 'Szerettel várunk mindenkit, aki ragyogóan tiszta autót szeretne magának, de nincsen ideje otthon kitakarítani, illetve lemosni. Prémium tisztító és ápoló szereink kíméletesen teszik csillogóan tisztává gépjárművedet!',
                'address' => '5700, Gyula, Nürnbergi u. 10.',
                'phone' => '+36-20-310-8586',
                'email' => null,
                'website' => null,
                'image' => 'pure_care_auto_kozmetika.jpg',
                'rating' => 5,
                'opening_hours' => 'hétfő 8:00–18:00, kedd 8:00–18:00, szerda 8:00–18:00, csütörtök 8:00–18:00, péntek 8:00–18:00, szombat 9:00–14:00, vasárnap Zárva',
                'features' => 'Autó külső és belső ápolása, wax, gumiápolás, kárpittisztítás.',
                'lat' => 46.650174,
                'lng' => 21.265941,
                'long_desc' => 'A Pure Care Autókozmetika a prémium autóápolás szakértője, ahol minden jármű különleges bánásmódban részesül. Célunk, hogy ügyfeleink autója ne csak tiszta legyen, hanem visszanyerje eredeti fényét és megjelenését. Szolgáltatásaink között megtalálható a külső-belső kézi autómosás, polírozás, kárpittisztítás, kerámia bevonat és fényezésvédelem is – mindezt professzionális eszközökkel és prémium minőségű anyagokkal végezzük.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automoso',
                'slug' => Str::slug('venus-auto-kozmetika'),
                'name' => 'VENUS Autókozmetika',
                'desc' => 'A Vénusz Autókozmetika gondoskodik arról, hogy autód mindig makulátlan és ápolt legyen. Szolgáltatásaink között megtalálható a kézi autómosás, belső tisztítás, viaszolás és karbantartó kozmetika – precízen, megbízhatóan, barátságos áron.',
                'address' => '5700, Gyula, Kálvária 3.',
                'phone' => '+36-20-350-8910',
                'email' => null,
                'website' => 'https://www.facebook.com/Venusauto2020/',
                'image' => 'venus_auto_kozmetika.jpg',
                'rating' => 5,
                'opening_hours' => 'hétfő 8:00–16:00, kedd 8:00–16:00, szerda 8:00–16:00, csütörtök 8:00–16:00, péntek 8:00–16:00, szombat Zárva, vasárnap Zárva',
                'features' => 'Ózonos fertőtlenítés, külső-belső tisztítás és ápolás, külső-belső műanyag elemek tisztítása, polírozás, kerámia, wax telepítés, fényszóró polírozás, üvegfelületek tisztítása, motortér tisztítás, felni tisztítás, ápolás.',
                'lat' => 46.635830,
                'lng' => 21.259117,
                'long_desc' => 'A Vénusz Autókozmetika olyan hely, ahol az autóápolás nem csak munka, hanem szenvedély. Célunk, hogy minden jármű tisztán, igényesen és újszerű állapotban térjen vissza tulajdonosához. Legyen szó egy gyors külső tisztításról vagy teljes belső-külső kozmetikáról, csapatunk precízen, odafigyeléssel dolgozik – mert hisszük, hogy a részletekben rejlik a minőség.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automentok',
                'slug' => Str::slug('automento-gyula'),
                'name' => 'Autómentő Gyula',
                'desc' => 'Legyen szó egy lerobbant gépjárműről, mi mindig rendelkezésedre állunk!',
                'address' => '5700, Gyula, Nagyfenék 37.',
                'phone' => '+36-20-358-6113',
                'email' => 'automento.gyula@gmail.com',
                'website' => 'https://automentogyula.hu',
                'image' => 'hajdu_lajos_automento.jpg',
                'rating' => 5.0,
                'opening_hours' => '0-24 ügyelet',
                'features' => 'Autómentés, gépszállítás, darus autómentés, daruzás, műszaki mentés.',
                'lat' => 46.685650,
                'lng' => 21.269330,
                'long_desc' => 'A Gyulai Autómentő gyors és megbízható segítséget nyújt a nap 24 órájában, legyen szó műszaki hibáról vagy balesetről. Korszerű járműveikkel biztonságosan szállítják el autóját, akár azonnali indulással is, Gyulán és környékén.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automentok',
                'slug' => Str::slug('car-potlas-automento'),
                'name' => 'Car-Pótlás Autóbontó-autómentés',
                'desc' => '3,5 tonna önsúlyig éjjel-nappal, bel- és külföldről is vállaljuk autók szállítását.',
                'address' => '5700, Gyula, 44-es főút, 134.km',
                'phone' => '+36-30-638-8398',
                'email' => 'matyitomi@yahoo.com',
                'website' => 'http://www.carpotlas.hu/index.php',
                'image' => 'car-potlas.jpg',
                'rating' => 4.6,
                'opening_hours' => '0-24',
                'features' => 'Autómentés, autóbontás, alkatrészkereskedelem, gépszállítás.',
                'lat' => 46.653616,
                'lng' => 21.230711,
                'long_desc' => 'Gyulán és környékén nyújt gyors, megbízható segítséget 0–24 órában. Hidroplatós járműveikkel akár 3,5 tonnáig vállalnak mentést, baleset vagy meghibásodás esetén is, több évtizedes tapasztalattal.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'automentok',
                'slug' => Str::slug('hajdu-lajos-automento'),
                'name' => 'Hajdu Lajos Ev.',
                'desc' => 'Egész nap rendelkezésre álló autómentő szolgáltatás Gyulán, akár tehergépkocsi számára is.',
                'address' => '5700, Gyula, Pap u. 4.',
                'phone' => '+36-30-945-1942',
                'email' => 'automentes@t-email.hu',
                'website' => null,
                'image' => null,
                'rating' => 4.7,
                'opening_hours' => '0-24',
                'features' => 'Autómentés, autószállítás, darus autómentő, gumi szerviz, kamionmentés.',
                'lat' => 46.642741,
                'lng' => 21.260858,
                'long_desc' => 'Egész nap rendelkezésre álló autómentő szolgáltatás Gyulán, akár tehergépkocsi számára is, legyen szó balesetről vagy szimpla műszaki hibáról. Mobil gumiszervizként is hívható!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
